sudo: false

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-1.13-7.8.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack-1.13-7.10.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=7.8.4 STACK_YAML=stack-1.14-7.8.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack-1.14-7.10.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=7.8.4 STACK_YAML=stack-1.15-7.8.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack-1.15-7.10.yaml GHCOPTS=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3

before_install:
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
script:
  - stack --no-terminal --skip-ghc-check test
