flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- base-unicode-symbols-0.2.2.4
- data-accessor-0.2.2.7
- data-accessor-template-0.2.1.12
- data-accessor-transformers-0.2.1.6
- hspec-2.2.2
- hspec-core-2.2.2
- hspec-discover-2.2.2
- hspec-expectations-0.7.2
- pandoc-1.15.2.1
- quickcheck-io-0.1.2
- roman-numerals-0.5.1.5
- utility-ht-0.0.11
resolver: ghc-7.10.3
