flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- data-accessor-0.2.2.7
- data-accessor-template-0.2.1.12
- data-accessor-transformers-0.2.1.6
- pandoc-1.15.2.1
- roman-numerals-0.5.1.5
- text-1.2.2.0
- yaml-0.8.15.2
resolver: lts-4.2
